### ISSUE TITLE
Replacing part of assertion

### ISSUE THREAD

**Issue by jnyrup** [Meir017/fluentassertions.bestpractices#5]
When verifying multiple assertions against the same object, you often combine them with `.And`.
Currently it seems the codefixer is not aware of this concept.

```c#
actual.Should().NotBeNull()
    .And.NotBeEmpty()
    .And.HaveCount(2);
```

is replaced with

```c#
actual.Should().NotBeNullOrEmpty();
```

**Comment by Meir017** [comment]
I'm not sure how to approach this feature yet. I opened an issue on the Roslyn project, maybe they have a helper for something like this

https://github.com/dotnet/roslyn/issues/22698

**Comment by Meir017** [comment]
@jnyrup any idea what the code fix should be in the following case?
```cs
actual.Should().NotBeNull("collection should not be null")
    .And.NotBeEmpty("collection should not be empty")
    .And.HaveCount(2);
```

**Comment by jnyrup** [comment]
Are you referring to the problem about which `becauseArgs` to choose when merging `NotBeNull` and `NotBeEmpty`?

If it was my own code using FA I would just write:
```c#
actual.Should().NotBeNullOrEmpty("collection should not be empty")
    .And.HaveCount(2);
```

But of course the analyzer needs to be general.
How about this:

* If both `NotBeNull` and `NotBeEmpty` has an `becauseArgs` suggest they could be merged, but without providing a codefix,
* otherwise merge them and there is at most a single `becauseArgs`.

**Comment by Meir017** [comment]
just came up with a way to do the replacement - here is a snippet https://gist.github.com/Meir017/48eef45a5b2525ce21ff12de0bae5dc0

**Comment by Meir017** [comment]
started work on the branch [feature/replacing-part-of-assertion](https://github.com/Meir017/fluentassertions.bestpractices/tree/feature/replacing-part-of-assertion)

**Comment by jnyrup** [comment]
Sounds great! 
My colleagues are already eager to know when they can start using this tool.

**Comment by Meir017** [comment]
@jnyrup 0.4.0 is up on NuGet now
